name: Format Check

on:
  workflow_call:

permissions:
  contents: read

jobs:
  format:
    name: treefmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Install Go formatters
        run: go install mvdan.cc/gofumpt@latest && go install github.com/daixiang0/gci@latest

      - name: Install shell tools
        run: |
          sudo apt-get install -y shellcheck
          go install mvdan.cc/sh/v3/cmd/shfmt@latest

      - name: Install prettier
        run: npm install -g prettier

      - name: Run treefmt
        uses: isbecker/treefmt-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-change: true
